name: Build and Deploy

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    uses: Integrosa/.github/.github/workflows/reusable-docker-build.yml@v1
    with:
      organization_name: "integrosa"
      project_name: "my-app"
      runs_on: "homelab"

  deploy:
    needs: build
    uses: Integrosa/.github/.github/workflows/reusable-k8s-deploy-pr.yml@v1
    with:
      app_name: "my-app"
      k8s_namespace: "k3s/apps/my-app"
      docker_image_path: ${{ needs.build.outputs.docker_image_path }}
      docker_image_full: ${{ needs.build.outputs.docker_image_full }}
      version_tag: ${{ needs.build.outputs.version_tag }}
    secrets:
      iac_token: ${{ secrets.ARGOCD_IAC_UPDATE_TOKEN }}
